{1} tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_attach_attached_volume_to_different_server [2.078661s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:49,690 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:49,691 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:50,500 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.808s
2022-07-20 17:05:50,501 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-324477502"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:49 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2304', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-905c9fa7-d68a-4e39-b57b-a6caf374c2de', 'x-compute-request-id': 'req-905c9fa7-d68a-4e39-b57b-a6caf374c2de', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEpAIBAAKCAQEAxfYvGd4+NXBAbl/leXnsULxTeVp16t+3xZwb+idtZzyyNg9r\\n64X1o/oUJqgEXOk+An7APay1rVy6mpwNYv2mHzs88mfKEcuy9k8A2E+0Y/Hboaz2\\nadzxa7VqLFRXyCZbexaimcUCFUtMaKrNLYC8tiTYPJEM3sheHlqmyeh92cVagvVZ\\nj49MJ0yTh3r0KD6yLhrDF3EhLR6mnCbc7T1CQ9+hoxmbl8jfyU1V3EVv8Q19WKAq\\nAkAnYeRtpGgsnpoQ3QPvVw3FPaLDc/X/SRxvezPxVwfL+ISHxmOrdQ4U07FnZ9UP\\nhPR8XFfUgKAa2r1C5QaUgWsEb4jqyWtpBHc7fQIDAQABAoIBAQCJ5l2XQobJSQHJ\\nIYpEHdetwhLQBWEBFYj54i5nCxIeCV0HZaTC85VS/gENkJtBccUdjdgy3l3Mfz0K\\nOMzmeVVAik6BeiV8Ug6/n/cxuAwsVy2tKUSaKCwQ4NYuPS7NIVM2omTwgxlZZhO7\\nEchN+1D5/R6Yyl5RzvgpYvKu0gLhMGyM8r6Q19RC0YL2sLbovrrV53E0+2Rvla4E\\nz6ANcb+2/lr+oYlejZ8kYPnd+qlrJcRzrAFw8d+nhanseJWj4iysBiMd3Uit/isW\\nsi3b2gejEGgTQNvvXQBQtP6BQmtjO6Kh3ZdA4kQ1CguopMTO/TXyjO2BtAsYL/vW\\nm5RfsgnNAoGBAOZZTCpk1X007LA4RoK/K3GNE8Esf5PCHOW0/reA88oRq5tzJ0Xb\\n5ujbzQuqw+yihaZ09tEyZkEYK0OWmiJBSQb6kTVQw8iQ979t2qT3d47ucJFEYnQI\\nvvwnsvNncdnLH4HCk8hMH7HH8lWexHqYqj66RxCrZ16y5lEJAYyF03nnAoGBANwB\\nms8uAnVz6NSQ69ESdqjGHSrzgLzvrKljTExyAI3Xso7QhUB5rizcYAdEldfynHRz\\n1XXruuAbNQgmbiJt6nUJmdUrqS7K/R1rysUJEQsdseEJU5iXDMStkigj8giAHz8a\\n5NOPBX36sWgCzLf8IEGICRRmXZCpmlFx6VqbMNr7AoGBAMILZ4Yu+0lGVDz+qydp\\nM4eseH+6pJ4sX3uCRTEAiF4pFI8XKnZHEPYIc2rop7OoFT5sOZ9w/YLIgWmmbKF+\\nra4bVke7ibJjrNCuEgn2DdlyM5GsMePdmkWAi9dPxTDbU+dTqnqI5go1jYdi/9Dm\\n2kONWGBKhAHaYvrQw2VFNyjxAoGACttBamvYzzbzDFpCaMTCej2cftwZRDmHiaxO\\nvY76nAVC2G1Nxgq7H5eYXYNy6X8dXVnB9Nm3FQwCp+5NjQFjinb40l4fMSHvL558\\nGREDeEr01igBqgv6I1J1Xem4Ldc0s4Z+ODpciQTv8DQDKikU5mbyG8GZaGQWK2K1\\nozT5SjUCgYAiQcbtzPSjt74KAlpnmS4RW0+cbH54lfLRTBK7uwT+/kGyNwTzY1Ni\\ns9awRZJuF+3uoOlMb6OVtloz/d38vPvTF3UCvH1NsQVOSf4yQgtnKw3mgxB4QxIi\\nKAeLwvDWQyEVSJjSbDtO8bagvkQWqH5t3wt0/PePQ6Ji3LpRVbXfHw==\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-324477502", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF9i8Z3j41cEBuX+V5eexQvFN5WnXq37fFnBv6J21nPLI2D2vrhfWj+hQmqARc6T4CfsA9rLWtXLqanA1i/aYfOzzyZ8oRy7L2TwDYT7Rj8duhrPZp3PFrtWosVFfIJlt7FqKZxQIVS0xoqs0tgLy2JNg8kQzeyF4eWqbJ6H3ZxVqC9VmPj0wnTJOHevQoPrIuGsMXcSEtHqacJtztPUJD36GjGZuXyN/JTVXcRW/xDX1YoCoCQCdh5G2kaCyemhDdA+9XDcU9osNz9f9JHG97M/FXB8v4hIfGY6t1DhTTsWdn1Q+E9HxcV9SAoBravULlBpSBawRviOrJa2kEdzt9 Generated-by-Nova", "fingerprint": "42:d2:f7:96:5b:ec:6d:24:c4:14:05:7b:16:9a:55:c0", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:50,506 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-324477502 created
2022-07-20 17:05:51,714 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 1.206s
2022-07-20 17:05:51,715 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'app
    lication/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:50 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-f1a5015e-c5ce-4772-886f-7706c21fb2fe', 'x-compute-request-id': 'req-f1a5015e-c5ce-4772-886f-7706c21fb2fe', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:51,715 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAxfYvGd4+NXBAbl/leXnsULxTeVp16t+3xZwb+idtZzyyNg9r\n64X1o/oUJqgEXOk+An7APay1rVy6mpwNYv2mHzs88mfKEcuy9k8A2E+0Y/Hboaz2\nadzxa7VqLFRXyCZbexaimcUCFUtMaKrNLYC8tiTYPJEM3sheHlqmyeh92cVagvVZ\nj49MJ0yTh3r0KD6yLhrDF3EhLR6mnCbc7T1CQ9+hoxmbl8jfyU1V3EVv8Q19WKAq\nAkAnYeRtpGgsnpoQ3QPvVw3FPaLDc/X/SRxvezPxVwfL+ISHxmOrdQ4U07FnZ9UP\nhPR8XFfUgKAa2r1C5QaUgWsEb4jqyWtpBHc7fQIDAQABAoIBAQCJ5l2XQobJSQHJ\nIYpEHdetwhLQBWEBFYj54i5nCxIeCV0HZaTC85VS/gENkJtBccUdjdgy3l3Mfz0K\nOMzmeVVAik6BeiV8Ug6/n/cxuAwsVy2tKUSaKCwQ4NYuPS7NIVM2omTwgxlZZhO7\nEchN+1D5/R6Yyl5RzvgpYvKu0gLhMGyM8r6Q19RC0YL2sLbovrrV53E0+2Rvla4E\nz6ANcb+2/lr+oYlejZ8kYPnd+qlrJcRzrAFw8d+nhanseJWj4iysBiMd3Uit/isW\nsi3b2gejEGgTQNvvXQBQtP6BQmtjO6Kh3ZdA4kQ1CguopMTO/TXyjO2BtAsYL/vW\nm5RfsgnNAoGBAOZZTCpk1X007LA4RoK/K3GNE8Esf5PCHOW0/reA88oRq5tzJ0Xb\n5ujbzQuqw+yihaZ09tEyZkEYK0OWmiJBSQb6kTVQw8iQ979t2qT3d47ucJFEYnQI\nvvwnsvNncdnLH4HCk8hMH7HH8lWexHqYqj66RxCrZ16y5lEJAYyF03nnAoGBANwB\nms8uAnVz6NSQ69ESdqjGHSrzgLzvrKljTExyAI3Xso7QhUB5rizcYAdEldfynHRz\n1XXruuAbNQgmbiJt6nUJmdUrqS7K/R1rysUJEQsdseEJU5iXDMStkigj8giAHz8a\n5NOPBX36sWgCzLf8IEGICRRmXZCpmlFx6VqbMNr7AoGBAMILZ4Yu+0lGVDz+qydp\nM4eseH+6pJ4sX3uCRTEAiF4pFI8XKnZHEPYIc2rop7OoFT5sOZ9w/YLIgWmmbKF+\nra4bVke7ibJjrNCuEgn2DdlyM5GsMePdmkWAi9dPxTDbU+dTqnqI5go1jYdi/9Dm\n2kONWGBKhAHaYvrQw2VFNyjxAoGACttBamvYzzbzDFpCaMTCej2cftwZRDmHiaxO\nvY76nAVC2G1Nxgq7H5eYXYNy6X8dXVnB9Nm3FQwCp+5NjQFjinb40l4fMSHvL558\nGREDeEr01igBqgv6I1J1Xem4Ldc0s4Z+ODpciQTv8DQDKikU5mbyG8GZaGQWK2K1\nozT5SjUCgYAiQcbtzPSjt74KAlpnmS4RW0+cbH54lfLRTBK7uwT+/kGyNwTzY1Ni\ns9awRZJuF+3uoOlMb6OVtloz/d38vPvTF3UCvH1NsQVOSf4yQgtnKw3mgxB4QxIi\nKAeLwvDWQyEVSJjSbDtO8bagvkQWqH5t3wt0/PePQ6Ji3LpRVbXfHw==\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-324477502', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF9i8Z3j41cEBuX+V5eexQvFN5WnXq37fFnBv6J21nPLI2D2vrhfWj+hQmqARc6T4CfsA9rLWtXLqanA1i/aYfOzzyZ8oRy7L2TwDYT7Rj8duhrPZp3PFrtWosVFfIJlt7FqKZxQIVS0xoqs0tgLy2JNg8kQzeyF4eWqbJ6H3ZxVqC9VmPj0wnTJOHevQoPrIuGsMXcSEtHqacJtztPUJD36GjGZuXyN/JTVXcRW/xDX1YoCoCQCdh5G2kaCyemhDdA+9XDcU9osNz9f9JHG97M/FXB8v4hIfGY6t1DhTTsWdn1Q+E9HxcV9SAoBravULlBpSBawRviOrJa2kEdzt9 Generated-by-Nova', 'fingerprint': '42:d2:f7:96:5b:ec:6d:24:c4:14:05:7b:16:9a:55:c0', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:51,763 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-324477502 0.046s
2022-07-20 17:05:51,763 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:51 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-87d1417d-bde1-4e12-a9d8-8c84768190fa', 'x-compute-request-id': 're
    q-87d1417d-bde1-4e12-a9d8-8c84768190fa', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-324477502'}
        Body: b''

{1} tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_attach_attached_volume_to_same_server [0.527512s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:51,772 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:51,773 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:52,185 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.412s
2022-07-20 17:05:52,186 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-1017563030"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:51 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2301', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-06fd85b0-7687-4123-bf0e-d0e37ad0c54b', 'x-compute-request-id': 'req-06fd85b0-7687-4123-bf0e-d0e37ad0c54b', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEowIBAAKCAQEA2QoR/6xRmpZ0TO1W7R9qurwhcEunnRoReetC/AGMCOYxHqe9\\nUAS9iw+wlXPZszLNtJhFnk+yUVxb/TIB0iYBmZ6wh9EDNjwlQQLgcQgLiXeKQsIa\\npCJOmd/0Dw2BpKWhXLsITxdwKwZcHzP3vk51ozZ2J7pz7nLOsrCVFXdZZoAJVwdR\\nz5xszoVKLFuZ1fMl4MyB40q/jPD6utWDx5uugk4ZMTi7C4BkAwIRywBje1hxCleJ\\nZy6wLGX5WyCqcqjpHP4MaqMvgT8fcrplz2YAuJPyH1Faco/1SQQFMp0Tv1UaSi5A\\nmAGPrndhInRh3lhWXi1JGmZtJ8wd08/D+2ra5wIDAQABAoIBAB5iiYiIwFfrDlci\\ntxO1XUTNR8Un4kxdNOsjo5oSQV+RknjfNOK59ys7xBX4RRcQWroYw05Zi/ZV/s7g\\nrF6WUY0HKWGqQk/adcC3PWK1pJ/XK3UTJZWq8+QY9VsSIf9B7OhFivE/r8VmO4lm\\nxh1PcKqr2jjPoqFUU1my3PxHXC28JwZUDhyecv0WIt2udzKIsdpv6hYqD6FxJV+F\\ngyRK++/JhiaQZCas8OtDA0hqtaxKTcdE3OAuGvIp/EQ358nkw3LIQkqqHzB6y0mC\\noSF6iVU1acR2nBnO9SfG7l9j//Hjm77HFo+/j98sRJafimC5B25J3U54dEWOJrqG\\nGdRv6ekCgYEA9NkcrfJhoRrzy9sqDRNaYSObC34cXxTCDbVOyyG/IITbyavv44Ef\\nobyeDIcdLUV85D5QJr4PjkqkrxyfjQKl/W53tPLiJQ5zaFDtxOhrp9g3N0FPTVML\\nROhZ9ZemyIY1D4X/N/2zDbFJfdmRAfV1Nrm/zvStpGIi3332Cg2f3yMCgYEA4uy2\\neqmDBEypoUFkTon1ecpz/nFXnx+EbCbmbyjiqKSJxyI3t9eUePFuaawSz1YHdzZ8\\nES+U2NPADOHWWuk605ZQZ7yavE5pgdS1bJVKWOIu1PyiP47fieFflirQXaQ5o2gq\\n+nYH3ujkAp8hHx04RqPqy8BG86ER5UgSW3dF020CgYAVA+GDSI96nW6Za6kzUBrs\\nxXqURPG4c3aoaIxnwPC/oMegiqJfW4DUh/TkzGADt7gdev+0I5IAO4XhBcrn9nc6\\nxlV98W7ZkWD0biXKRcyfrl4m3vMoht0rv+mgu7Bz+5joSS77pknM/g95vsfEbEXw\\nOYcuAzA4MLgfiJcqi7rSEwKBgQDAoNAGL/7Xl3wnNqs/QDzwtbrhMrV+jfKLHDpg\\nAgTlw0Zxk8pYdNfEEq33ZepRtmV//PA0Zn+jz5wnU03yvikBk4eNh7ySPL2zSCz5\\nj4EdEmNOyWWxLkbzdCz//DgERXPoEnTpR2hHAMsMrqgfEV7EGEEn1IBmL0RRrWxn\\n2EedwQKBgBpvqOXljiZYhdGJUXReOdnGi2V1rBaDR8m+xEkmTJlECuguU4UCk/t4\\n2zqiTtCMUXurcYz+NdLcwaj4uTFjUfJqhNhvo7bJPVjlGeY1I/HWyU9EQSFcosWU\\nd9oC0D9VMEz+x/GIPdVkxuwSNZEfWf8fggryjnwNinGAuctLb8T8\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-1017563030", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZChH/rFGalnRM7VbtH2q6vCFwS6edGhF560L8AYwI5jEep71QBL2LD7CVc9mzMs20mEWeT7JRXFv9MgHSJgGZnrCH0QM2PCVBAuBxCAuJd4pCwhqkIk6Z3/QPDYGkpaFcuwhPF3ArBlwfM/e+TnWjNnYnunPucs6ysJUVd1lmgAlXB1HPnGzOhUosW5nV8yXgzIHjSr+M8Pq61YPHm66CThkxOLsLgGQDAhHLAGN7WHEKV4lnLrAsZflbIKpyqOkc/gxqoy+BPx9yumXPZgC4k/IfUVpyj/VJBAUynRO/VRpKLkCYAY+ud2EidGHeWFZeLUkaZm0nzB3Tz8P7atrn Generated-by-Nova", "fingerprint": "1d:46:7b:3a:a6:1d:e0:8f:cd:0e:94:ad:40:52:cf:b4", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:52,189 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-1017563030 created
2022-07-20 17:05:52,259 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 0.068s
2022-07-20 17:05:52,259 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'appl
    ication/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-1901deee-3f38-497d-8ca7-c9497a767f05', 'x-compute-request-id': 'req-1901deee-3f38-497d-8ca7-c9497a767f05', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:52,260 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA2QoR/6xRmpZ0TO1W7R9qurwhcEunnRoReetC/AGMCOYxHqe9\nUAS9iw+wlXPZszLNtJhFnk+yUVxb/TIB0iYBmZ6wh9EDNjwlQQLgcQgLiXeKQsIa\npCJOmd/0Dw2BpKWhXLsITxdwKwZcHzP3vk51ozZ2J7pz7nLOsrCVFXdZZoAJVwdR\nz5xszoVKLFuZ1fMl4MyB40q/jPD6utWDx5uugk4ZMTi7C4BkAwIRywBje1hxCleJ\nZy6wLGX5WyCqcqjpHP4MaqMvgT8fcrplz2YAuJPyH1Faco/1SQQFMp0Tv1UaSi5A\nmAGPrndhInRh3lhWXi1JGmZtJ8wd08/D+2ra5wIDAQABAoIBAB5iiYiIwFfrDlci\ntxO1XUTNR8Un4kxdNOsjo5oSQV+RknjfNOK59ys7xBX4RRcQWroYw05Zi/ZV/s7g\nrF6WUY0HKWGqQk/adcC3PWK1pJ/XK3UTJZWq8+QY9VsSIf9B7OhFivE/r8VmO4lm\nxh1PcKqr2jjPoqFUU1my3PxHXC28JwZUDhyecv0WIt2udzKIsdpv6hYqD6FxJV+F\ngyRK++/JhiaQZCas8OtDA0hqtaxKTcdE3OAuGvIp/EQ358nkw3LIQkqqHzB6y0mC\noSF6iVU1acR2nBnO9SfG7l9j//Hjm77HFo+/j98sRJafimC5B25J3U54dEWOJrqG\nGdRv6ekCgYEA9NkcrfJhoRrzy9sqDRNaYSObC34cXxTCDbVOyyG/IITbyavv44Ef\nobyeDIcdLUV85D5QJr4PjkqkrxyfjQKl/W53tPLiJQ5zaFDtxOhrp9g3N0FPTVML\nROhZ9ZemyIY1D4X/N/2zDbFJfdmRAfV1Nrm/zvStpGIi3332Cg2f3yMCgYEA4uy2\neqmDBEypoUFkTon1ecpz/nFXnx+EbCbmbyjiqKSJxyI3t9eUePFuaawSz1YHdzZ8\nES+U2NPADOHWWuk605ZQZ7yavE5pgdS1bJVKWOIu1PyiP47fieFflirQXaQ5o2gq\n+nYH3ujkAp8hHx04RqPqy8BG86ER5UgSW3dF020CgYAVA+GDSI96nW6Za6kzUBrs\nxXqURPG4c3aoaIxnwPC/oMegiqJfW4DUh/TkzGADt7gdev+0I5IAO4XhBcrn9nc6\nxlV98W7ZkWD0biXKRcyfrl4m3vMoht0rv+mgu7Bz+5joSS77pknM/g95vsfEbEXw\nOYcuAzA4MLgfiJcqi7rSEwKBgQDAoNAGL/7Xl3wnNqs/QDzwtbrhMrV+jfKLHDpg\nAgTlw0Zxk8pYdNfEEq33ZepRtmV//PA0Zn+jz5wnU03yvikBk4eNh7ySPL2zSCz5\nj4EdEmNOyWWxLkbzdCz//DgERXPoEnTpR2hHAMsMrqgfEV7EGEEn1IBmL0RRrWxn\n2EedwQKBgBpvqOXljiZYhdGJUXReOdnGi2V1rBaDR8m+xEkmTJlECuguU4UCk/t4\n2zqiTtCMUXurcYz+NdLcwaj4uTFjUfJqhNhvo7bJPVjlGeY1I/HWyU9EQSFcosWU\nd9oC0D9VMEz+x/GIPdVkxuwSNZEfWf8fggryjnwNinGAuctLb8T8\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-1017563030', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZChH/rFGalnRM7VbtH2q6vCFwS6edGhF560L8AYwI5jEep71QBL2LD7CVc9mzMs20mEWeT7JRXFv9MgHSJgGZnrCH0QM2PCVBAuBxCAuJd4pCwhqkIk6Z3/QPDYGkpaFcuwhPF3ArBlwfM/e+TnWjNnYnunPucs6ysJUVd1lmgAlXB1HPnGzOhUosW5nV8yXgzIHjSr+M8Pq61YPHm66CThkxOLsLgGQDAhHLAGN7WHEKV4lnLrAsZflbIKpyqOkc/gxqoy+BPx9yumXPZgC4k/IfUVpyj/VJBAUynRO/VRpKLkCYAY+ud2EidGHeWFZeLUkaZm0nzB3Tz8P7atrn Generated-by-Nova', 'fingerprint': '1d:46:7b:3a:a6:1d:e0:8f:cd:0e:94:ad:40:52:cf:b4', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:52,297 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-1017563030 0.036s
2022-07-20 17:05:52,298 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-b457e327-bb0d-4ecc-9ec0-86da7e0c918d', 'x-compute-request-id': 'req-b
    457e327-bb0d-4ecc-9ec0-86da7e0c918d', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-1017563030'}
        Body: b''

{2} tempest.api.compute.volumes.test_volumes_get.VolumesGetTestJSON.test_volume_create_get_delete [2.787667s] ... ok
{1} tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_delete_attached_volume [0.293608s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:52,304 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:52,305 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:52,450 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.145s
2022-07-20 17:05:52,451 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-568944202"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2300', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-76f5124f-d800-4f11-b141-c9ea4da40397', 'x-compute-request-id': 'req-76f5124f-d800-4f11-b141-c9ea4da40397', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEogIBAAKCAQEAwmdheM+MLKcROecta5ZWt1HvUpehE7AfqdNIOWqWZlOvcQZK\\nOlvfFiZFlS3wWsYXD9OJjr0AiQLdejbc8hG5DHpBML59kDJLDjGhez5+7a8ujiA3\\nwMg9ohN3QjA5v0OfCHNH3jhrM1Jl7JLQ21deQXgfAqky4as/prr8w/wiIb63C9a2\\n5YvgQs7ftL4FaZhDEr39QC6Bwcj0nLrhSxhGe1XXy5isWyZes5ql7Cr2BLEQOLI8\\n7B7UsrqcZyA2Pbi7hTHaNmWDaP8jBUGbefxbqoeV7rxGt1NLK+wysP3Eo41sYSYD\\nlMGOgB6qR5360FokfhndGp7JkJ4BPDnJWGiMLwIDAQABAoIBABG9FSvM5GF+rRe3\\nfHGAulDn7QqAQ3Zkb78zRDfY/fhAUpXhmQxSLbz7qQW/t1rREHGlP7wCivX1iPgJ\\n4YdFDrmQvjoQZ6ysqiSVasKwJSzS+1CEqBGzM8yCMjOb6ukE5pIC0t/4DfAU6K/5\\nhY0+H5+hslKv1bC5y4kPLtlDPGoPsCzVa9TRmPSH6lAk6aeG2Wj//KJ6fGccJ7SM\\nw4bkBfsgFtVPeDmfel+RVcmZ9mIN0tD/18RkH2uGU078ztE1pv8sohbI3hN7l/aU\\nvpQS5mHJybt6oNEb8qxYRsJhSSWzDE5CSyUEzHCHcgDEswtY1o0X9a6V6fC/msek\\nxQ79feECgYEA6JBo89Y3fhiPelh3iq8OWUyLE3Uc4C7wLWnaXtk+1kw0ptRQhkpv\\nxLtVYIdoW+ui0ne4apW035u/w68DgDlSQe/7m4I/2mNIT8Lxm27IkS0VeIszelEY\\n2SriRnTVmB0hNzmTs6VL0LCfx/Wpq7RiGZrNztazgGerf1I67bLhuyUCgYEA1f6H\\nP3QgmAOCveM+WrA+L6VC8ImFxy1zSPdwANUvtF+AUMGV/vnzj+hbpSkuI8WndiQu\\nBChbEVvp8ank+0gwspHNkJSDSlAhh6Z0xD8x+TVY9qKIySg1JXLJD+jvADfQ+wyT\\nc2k2UjdxE6CbnbSL6RJHp+12IwgA6V+nqwaCU8MCgYAEV+4d37pZmIvVdSGGbY6P\\nDGbsjhtj9Hx33Ko/az9JMVMqany2hV1hBz6o9t50GQqJc8L1+qXOJ1KFjRc7pdZr\\ndNf2J5CZu5D2LGXmyULlsznbbn4forQcGjjvp+71UFX2ehTQHh40X5gcW/I3Sr8q\\nS0HcwxXHKCiD0D1ZgyXEIQKBgHCTZzk1cVQnPKeCnbH916kfCpkZ79u5iFWRfkWh\\n4WfFee6B+NPbUIubVGMNx+0ftRpMrDyZslbugKMWmpSrBJtcYsU1q9/zScBgDDuV\\nd0fADd4p4UXZtiPOQAHzq4/0zSbVFdj4N5CHBCCsNFGBwrzJVhL8tFJ3ims7XCx3\\nzyYbAoGAFj+ruYL6UFQtfa+VowUb0JKJnHe2fe2kxMxYmRASIK73Zu1Yq6iO6jvO\\nLhuZB+FcdmOjBM5GKvFnH8X4JTKGd8qCdddBcKn19MBa5Fd8X1X9ncoYNIN9WDiL\\nEgYVNgeU4SNsukSLn8RcGZwCsfv5OoTT1LPaXAOgs1H8n8lfSJ8=\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-568944202", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZ2F4z4wspxE55y1rlla3Ue9Sl6ETsB+p00g5apZmU69xBko6W98WJkWVLfBaxhcP04mOvQCJAt16NtzyEbkMekEwvn2QMksOMaF7Pn7try6OIDfAyD2iE3dCMDm/Q58Ic0feOGszUmXsktDbV15BeB8CqTLhqz+muvzD/CIhvrcL1rbli+BCzt+0vgVpmEMSvf1ALoHByPScuuFLGEZ7VdfLmKxbJl6zmqXsKvYEsRA4sjzsHtSyupxnIDY9uLuFMdo2ZYNo/yMFQZt5/Fuqh5XuvEa3U0sr7DKw/cSjjWxhJgOUwY6AHqpHnfrQWiR+Gd0ansmQngE8OclYaIwv Generated-by-Nova", "fingerprint": "70:c8:f3:29:c7:e0:b8:29:e7:5a:92:cd:33:65:57:78", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:52,454 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-568944202 created
2022-07-20 17:05:52,561 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 0.106s
2022-07-20 17:05:52,562 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'applica
    tion/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-076629df-42e8-4d01-8453-5406b16870bc', 'x-compute-request-id': 'req-076629df-42e8-4d01-8453-5406b16870bc', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:52,562 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAwmdheM+MLKcROecta5ZWt1HvUpehE7AfqdNIOWqWZlOvcQZK\nOlvfFiZFlS3wWsYXD9OJjr0AiQLdejbc8hG5DHpBML59kDJLDjGhez5+7a8ujiA3\nwMg9ohN3QjA5v0OfCHNH3jhrM1Jl7JLQ21deQXgfAqky4as/prr8w/wiIb63C9a2\n5YvgQs7ftL4FaZhDEr39QC6Bwcj0nLrhSxhGe1XXy5isWyZes5ql7Cr2BLEQOLI8\n7B7UsrqcZyA2Pbi7hTHaNmWDaP8jBUGbefxbqoeV7rxGt1NLK+wysP3Eo41sYSYD\nlMGOgB6qR5360FokfhndGp7JkJ4BPDnJWGiMLwIDAQABAoIBABG9FSvM5GF+rRe3\nfHGAulDn7QqAQ3Zkb78zRDfY/fhAUpXhmQxSLbz7qQW/t1rREHGlP7wCivX1iPgJ\n4YdFDrmQvjoQZ6ysqiSVasKwJSzS+1CEqBGzM8yCMjOb6ukE5pIC0t/4DfAU6K/5\nhY0+H5+hslKv1bC5y4kPLtlDPGoPsCzVa9TRmPSH6lAk6aeG2Wj//KJ6fGccJ7SM\nw4bkBfsgFtVPeDmfel+RVcmZ9mIN0tD/18RkH2uGU078ztE1pv8sohbI3hN7l/aU\nvpQS5mHJybt6oNEb8qxYRsJhSSWzDE5CSyUEzHCHcgDEswtY1o0X9a6V6fC/msek\nxQ79feECgYEA6JBo89Y3fhiPelh3iq8OWUyLE3Uc4C7wLWnaXtk+1kw0ptRQhkpv\nxLtVYIdoW+ui0ne4apW035u/w68DgDlSQe/7m4I/2mNIT8Lxm27IkS0VeIszelEY\n2SriRnTVmB0hNzmTs6VL0LCfx/Wpq7RiGZrNztazgGerf1I67bLhuyUCgYEA1f6H\nP3QgmAOCveM+WrA+L6VC8ImFxy1zSPdwANUvtF+AUMGV/vnzj+hbpSkuI8WndiQu\nBChbEVvp8ank+0gwspHNkJSDSlAhh6Z0xD8x+TVY9qKIySg1JXLJD+jvADfQ+wyT\nc2k2UjdxE6CbnbSL6RJHp+12IwgA6V+nqwaCU8MCgYAEV+4d37pZmIvVdSGGbY6P\nDGbsjhtj9Hx33Ko/az9JMVMqany2hV1hBz6o9t50GQqJc8L1+qXOJ1KFjRc7pdZr\ndNf2J5CZu5D2LGXmyULlsznbbn4forQcGjjvp+71UFX2ehTQHh40X5gcW/I3Sr8q\nS0HcwxXHKCiD0D1ZgyXEIQKBgHCTZzk1cVQnPKeCnbH916kfCpkZ79u5iFWRfkWh\n4WfFee6B+NPbUIubVGMNx+0ftRpMrDyZslbugKMWmpSrBJtcYsU1q9/zScBgDDuV\nd0fADd4p4UXZtiPOQAHzq4/0zSbVFdj4N5CHBCCsNFGBwrzJVhL8tFJ3ims7XCx3\nzyYbAoGAFj+ruYL6UFQtfa+VowUb0JKJnHe2fe2kxMxYmRASIK73Zu1Yq6iO6jvO\nLhuZB+FcdmOjBM5GKvFnH8X4JTKGd8qCdddBcKn19MBa5Fd8X1X9ncoYNIN9WDiL\nEgYVNgeU4SNsukSLn8RcGZwCsfv5OoTT1LPaXAOgs1H8n8lfSJ8=\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-568944202', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZ2F4z4wspxE55y1rlla3Ue9Sl6ETsB+p00g5apZmU69xBko6W98WJkWVLfBaxhcP04mOvQCJAt16NtzyEbkMekEwvn2QMksOMaF7Pn7try6OIDfAyD2iE3dCMDm/Q58Ic0feOGszUmXsktDbV15BeB8CqTLhqz+muvzD/CIhvrcL1rbli+BCzt+0vgVpmEMSvf1ALoHByPScuuFLGEZ7VdfLmKxbJl6zmqXsKvYEsRA4sjzsHtSyupxnIDY9uLuFMdo2ZYNo/yMFQZt5/Fuqh5XuvEa3U0sr7DKw/cSjjWxhJgOUwY6AHqpHnfrQWiR+Gd0ansmQngE8OclYaIwv Generated-by-Nova', 'fingerprint': '70:c8:f3:29:c7:e0:b8:29:e7:5a:92:cd:33:65:57:78', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:52,595 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-568944202 0.031s
2022-07-20 17:05:52,595 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-ec95a74a-ff11-445c-b40d-34a7ef8c6146', 'x-compute-request-id': 'req-ec95a7
    4a-ff11-445c-b40d-34a7ef8c6146', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-568944202'}
        Body: b''

{1} tempest.api.volume.admin.test_encrypted_volumes_extend.EncryptedVolumesExtendAttachedTest.test_extend_attached_encrypted_volume_luksv1 ... SKIPPED: Attached encrypted volume extend is disabled.
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list [0.075176s] ... ok
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list_param_limit [0.067377s] ... ok
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list_param_offset_and_limit [0.141008s] ... ok
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list_with_detail_param_limit [0.065443s] ... ok
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list_with_detail_param_offset_and_limit [0.132852s] ... ok
{2} tempest.api.compute.volumes.test_volumes_list.VolumesTestJSON.test_volume_list_with_details [0.079786s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_invalid_size [0.163355s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_size_zero [0.016088s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_create_volume_without_passing_size [0.018014s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_delete_invalid_volume_id [0.051177s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_delete_volume_without_passing_volume_id [0.011912s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_get_volume_without_passing_volume_id [0.012472s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_volume_delete_nonexistent_volume_id [0.052094s] ... ok
{1} tempest.api.volume.admin.test_group_snapshots.GroupSnapshotsV319Test.test_reset_group_snapshot_status [9.166674s] ... ok
{2} tempest.api.compute.volumes.test_volumes_negative.VolumesNegativeTest.test_volume_get_nonexistent_volume_id [0.050087s] ... ok
{0} tempest.api.compute.volumes.test_attach_volume.AttachVolumeMultiAttachTest.test_boot_from_multiattach_volume [25.403751s] ... ok
{1} tempest.api.volume.admin.test_group_type_specs.GroupTypeSpecsTest.test_group_type_specs_create_show_update_list_delete [0.596337s] ... ok
{2} tempest.api.volume.admin.test_group_snapshots.GroupSnapshotsTest.test_create_group_from_group_snapshot [12.364147s] ... ok
{1} tempest.api.volume.admin.test_groups.GroupsV314Test.test_create_group_from_group [9.317391s] ... ok
{1} tempest.api.volume.admin.test_groups.GroupsV320Test.test_reset_group_status [3.065803s] ... ok
{1} setUpClass (tempest.api.volume.admin.test_volume_manage.VolumeManageAdminTest) ... SKIPPED: Manage volume tests are disabled
{2} tempest.api.volume.admin.test_group_snapshots.GroupSnapshotsTest.test_delete_group_snapshots_following_updated_volumes [16.938414s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_delete_quota [0.358778s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_list_default_quotas [0.042690s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_list_quotas [0.050855s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_quota_usage [3.907062s] ... ok
{2} tempest.api.volume.admin.test_group_snapshots.GroupSnapshotsTest.test_group_snapshot_create_show_list_delete [8.738979s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_quota_usage_after_volume_transfer [4.430627s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_show_quota_usage [0.057490s] ... ok
{1} tempest.api.volume.admin.test_volume_quotas.VolumeQuotasAdminTestJSON.test_update_all_quota_resources_for_tenant [0.263734s] ... ok
{2} setUpClass (tempest.api.volume.admin.test_multi_backend.VolumeMultiBackendTest) ... SKIPPED: Cinder multi-backend feature disabled
{1} setUpClass (tempest.api.volume.admin.test_volume_retype.VolumeRetypeWithMigrationTest) ... SKIPPED: Cinder multi-backend feature disabled
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_reset_snapshot_status [0.225769s] ... ok
{1} tempest.api.volume.admin.test_volume_snapshot_quotas_negative.VolumeSnapshotQuotasNegativeTestJSON.test_quota_volume_gigabytes_snapshots [0.268003s] ... ok
{1} tempest.api.volume.admin.test_volume_snapshot_quotas_negative.VolumeSnapshotQuotasNegativeTestJSON.test_quota_volume_snapshots [0.065956s] ... ok
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_snapshot_force_delete_when_snapshot_is_creating [3.508024s] ... ok
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_snapshot_force_delete_when_snapshot_is_deleting [3.534604s] ... ok
{1} tempest.api.volume.admin.test_volume_types_negative.VolumeTypesNegativeTest.test_create_volume_type_encryption_nonexistent_type_id [0.182690s] ... ok
{1} tempest.api.volume.admin.test_volume_types_negative.VolumeTypesNegativeTest.test_create_with_empty_name [0.017351s] ... ok
{1} tempest.api.volume.admin.test_volume_types_negative.VolumeTypesNegativeTest.test_create_with_repeated_name [0.059014s] ... ok
{1} tempest.api.volume.admin.test_volume_types_negative.VolumeTypesNegativeTest.test_delete_nonexistent_type_id [0.022686s] ... ok
{1} tempest.api.volume.admin.test_volume_types_negative.VolumeTypesNegativeTest.test_get_nonexistent_type_id [0.022277s] ... ok
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_snapshot_force_delete_when_snapshot_is_error [3.502815s] ... ok
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_snapshot_force_delete_when_snapshot_is_error_deleting [3.537483s] ... ok
{2} tempest.api.volume.admin.test_snapshots_actions.SnapshotsActionsTest.test_update_snapshot_status [0.236057s] ... ok
{1} tempest.api.volume.test_snapshot_metadata.SnapshotMetadataTestJSON.test_crud_snapshot_metadata [0.299152s] ... ok
{1} tempest.api.volume.test_snapshot_metadata.SnapshotMetadataTestJSON.test_update_show_snapshot_metadata_item [0.263657s] ... ok
{1} tempest.api.volume.test_versions.VersionsTest.test_list_versions [0.014660s] ... ok
{1} tempest.api.volume.test_versions.VersionsTest.test_show_version [0.123329s] ... ok
{2} tempest.api.volume.admin.test_volume_quotas_negative.VolumeQuotasNegativeTestJSON.test_quota_volume_gigabytes [0.232631s] ... ok
{2} tempest.api.volume.admin.test_volume_quotas_negative.VolumeQuotasNegativeTestJSON.test_quota_volumes [0.208869s] ... ok
{2} tempest.api.volume.admin.test_volume_quotas_negative.VolumeQuotasNegativeTestJSON.test_volume_extend_gigabytes_quota_deviation [0.163677s] ... ok
{1} tempest.api.volume.test_volume_absolute_limits.AbsoluteLimitsTests.test_get_volume_absolute_limits [0.053729s] ... ok
{0} tempest.api.compute.volumes.test_attach_volume.AttachVolumeMultiAttachTest.test_list_get_volume_attachments_multiattach [79.288935s] ... ok
{0} tempest.api.compute.volumes.test_attach_volume.AttachVolumeMultiAttachTest.test_resize_server_with_multiattached_volume ... SKIPPED: Resize not available.
{2} tempest.api.volume.admin.test_volume_retype.VolumeRetypeWithoutMigrationTest.test_available_volume_retype [4.012340s] ... ok
{2} tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_get_service_by_host_name [0.030050s] ... ok
{2} tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_get_service_by_service_and_host_name [0.032374s] ... ok
{2} tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_get_service_by_service_binary_name [0.024975s] ... ok
{1} tempest.api.volume.test_volume_delete_cascade.VolumesDeleteCascade.test_volume_delete_cascade [8.204706s] ... ok
{2} tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_get_service_by_volume_host_name [2.637448s] ... ok
{2} tempest.api.volume.admin.test_volume_services.VolumesServicesTestJSON.test_list_services [0.026888s] ... ok
{1} tempest.api.volume.test_volume_delete_cascade.VolumesDeleteCascade.test_volume_from_snapshot_cascade_delete [7.374003s] ... ok
{2} tempest.api.volume.admin.test_volume_services_negative.VolumeServicesNegativeTest.test_disable_log_reason_with_no_reason [0.019670s] ... ok
{2} tempest.api.volume.admin.test_volume_services_negative.VolumeServicesNegativeTest.test_disable_service_with_invalid_binary [0.030301s] ... ok
{2} tempest.api.volume.admin.test_volume_services_negative.VolumeServicesNegativeTest.test_enable_service_with_invalid_host [0.030719s] ... ok
{2} tempest.api.volume.admin.test_volume_services_negative.VolumeServicesNegativeTest.test_freeze_host_with_invalid_host [0.029565s] ... ok
{2} tempest.api.volume.admin.test_volume_services_negative.VolumeServicesNegativeTest.test_thaw_host_with_invalid_host [0.029963s] ... ok
{0} tempest.api.compute.volumes.test_attach_volume.AttachVolumeMultiAttachTest.test_snapshot_volume_backed_multiattach [25.140932s] ... ok
{2} tempest.api.volume.admin.test_volume_type_access.VolumeTypesAccessTest.test_volume_type_access_list [0.361950s] ... ok
{2} tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_type_create_get_delete [0.180327s] ... ok
{2} tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_type_encryption_create_get_update_delete [0.321718s] ... ok
{2} tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_type_list [0.046194s] ... ok
{2} tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_type_update [0.151877s] ... ok
{2} tempest.api.volume.test_availability_zone.AvailabilityZoneTestJSON.test_get_availability_zone_list [0.203597s] ... ok
{2} tempest.api.volume.test_extensions.ExtensionsTestJSON.test_list_extensions [0.121332s] ... ok
{1} tempest.api.volume.test_volumes_clone.VolumesCloneTest.test_create_from_bootable_volume [17.474065s] ... ok
{0} tempest.api.compute.volumes.test_volume_snapshots.VolumesSnapshotsTestJSON.test_volume_snapshot_create_get_list_delete [6.364420s] ... ok
{1} tempest.api.volume.test_volumes_clone.VolumesCloneTest.test_create_from_volume [5.862433s] ... ok
{0} tempest.api.volume.admin.test_backends_capabilities.BackendsCapabilitiesAdminTestsJSON.test_compare_volume_stats_values [0.098355s] ... ok
{0} tempest.api.volume.admin.test_backends_capabilities.BackendsCapabilitiesAdminTestsJSON.test_get_capabilities_backend [0.040586s] ... ok
{2} tempest.api.volume.test_volume_transfers.VolumesTransfersV355Test.test_create_get_list_accept_volume_transfer [4.708030s] ... ok
{0} tempest.api.volume.admin.test_group_types.GroupTypesTest.test_group_type_create_list_update_show_delete [0.316517s] ... ok
{0} tempest.api.volume.admin.test_group_types.GroupTypesTest.test_group_type_list_by_optional_params [0.269038s] ... ok
{2} tempest.api.volume.test_volume_transfers.VolumesTransfersV355Test.test_create_list_delete_volume_transfer [3.803058s] ... ok
{1} tempest.api.volume.test_volumes_clone_negative.VolumesCloneNegativeTest.test_create_from_volume_decreasing_size [2.646674s] ... ok
{0} tempest.api.volume.admin.test_groups.GroupsTest.test_group_create_show_list_delete [8.079490s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_attach_detach_volume_to_instance [7.037711s] ... ok
{1} tempest.api.volume.test_volumes_get.VolumesGetTest.test_volume_create_get_update_delete [7.471360s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_get_volume_attachment [5.838960s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_reserve_unreserve_volume [0.195427s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_volume_bootable [0.192782s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_volume_readonly_update [0.217348s] ... ok
{0} tempest.api.volume.admin.test_groups.GroupsTest.test_group_update [10.120840s] ... ok
{1} tempest.api.volume.test_volumes_get.VolumesGetTest.test_volume_create_get_update_delete_as_clone [10.844744s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_associate_disassociate_qos [1.394222s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_create_delete_qos_with_back_end_consumer [0.167947s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_create_delete_qos_with_both_consumer [0.229575s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_create_delete_qos_with_front_end_consumer [1.134484s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_get_qos [0.027309s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_list_qos [0.032715s] ... ok
{0} tempest.api.volume.admin.test_qos.QosSpecsTestJSON.test_set_unset_qos_key [1.116969s] ... ok
{2} tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_volume_upload [15.916409s] ... ok
{0} setUpClass (tempest.api.volume.admin.test_snapshot_manage.SnapshotManageAdminTest) ... SKIPPED: Manage snapshot tests are disabled
{0} tempest.api.volume.admin.test_user_messages.UserMessagesTest.test_delete_message [1.759184s] ... ok
{0} tempest.api.volume.admin.test_user_messages.UserMessagesTest.test_list_show_messages [1.497983s] ... ok
{1} tempest.api.volume.test_volumes_get.VolumesGetTest.test_volume_create_get_update_delete_from_image [21.223378s] ... ok
{0} tempest.api.volume.admin.test_volume_hosts.VolumeHostsAdminTestsJSON.test_list_hosts [0.180654s] ... ok
{0} tempest.api.volume.admin.test_volume_hosts.VolumeHostsAdminTestsJSON.test_show_host [0.176664s] ... ok
{1} tempest.api.volume.test_volumes_get.VolumesSummaryTest.test_show_volume_summary [0.137704s] ... ok
{0} tempest.api.volume.admin.test_volume_pools.VolumePoolsAdminTestsJSON.test_get_pools_without_details [0.156329s] ... ok
{2} tempest.api.volume.test_volumes_extend.VolumesExtendTest.test_volume_extend [17.204821s] ... ok
{0} tempest.api.volume.admin.test_volume_quota_classes.VolumeQuotaClassesTest.test_show_default_quota [0.147143s] ... ok
{0} tempest.api.volume.admin.test_volume_quota_classes.VolumeQuotaClassesTest.test_update_default_quota [0.806987s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list [0.036650s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_by_name [0.035708s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_details_by_name [0.054344s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_details_pagination [0.233079s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_details_with_multiple_params [0.194448s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_pagination [0.170562s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_param_display_name_and_status [0.067783s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_with_detail_param_display_name_and_status [0.078577s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_with_detail_param_marker [0.099160s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_with_detail_param_metadata [0.092912s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_with_details [0.069494s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_with_param_metadata [0.044399s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_by_availability_zone [0.111346s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_by_bootable [0.079381s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_by_status [0.078103s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_details_by_availability_zone [0.056428s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_details_by_bootable [0.054232s] ... ok
{1} tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volumes_list_details_by_status [0.055795s] ... ok
{2} tempest.api.volume.test_volumes_extend.VolumesExtendTest.test_volume_extend_when_volume_has_snapshot [5.867473s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs.VolumeTypesExtraSpecsTest.test_volume_type_extra_spec_create_get_delete [0.175025s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs.VolumeTypesExtraSpecsTest.test_volume_type_extra_specs_list [0.089363s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs.VolumeTypesExtraSpecsTest.test_volume_type_extra_specs_update [0.235235s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_create_invalid_body [0.017545s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_create_none_body [0.016160s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_create_nonexistent_type_id [0.034675s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_delete_nonexistent_volume_type_id [0.025226s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_get_nonexistent_extra_spec_name [0.032226s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_get_nonexistent_volume_type_id [0.025975s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_list_nonexistent_volume_type_id [0.024702s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_update_multiple_extra_spec [0.017746s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_update_no_body [0.017934s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_update_none_extra_spec_id [0.042130s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_update_nonexistent_extra_spec_id [0.038214s] ... ok
{0} tempest.api.volume.admin.test_volume_types_extra_specs_negative.ExtraSpecsNegativeTest.test_update_nonexistent_type_id [0.040934s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_limit [0.035223s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_limit_equals_infinite [0.060975s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_limit_equals_zero [0.025674s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_marker [0.069331s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_offset [0.038266s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_created_at_asc [0.030389s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_created_at_desc [0.034168s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_id_asc [0.031714s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_attach_volumes_with_nonexistent_volume_id [6.712505s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_id_desc [0.060158s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_name_asc [0.029401s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshot_list_param_sort_name_desc [0.032088s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshots_list_details_with_params [0.114848s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_list.VolumesSnapshotListTestJSON.test_snapshots_list_with_params [0.091449s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_from_deactivated_image [0.520556s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_from_image_with_decreasing_size [0.358851s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_invalid_size [0.016200s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_nonexistent_snapshot_id [0.026816s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_nonexistent_source_volid [0.025694s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_nonexistent_volume_type [0.024943s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_size_negative [0.015508s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_with_size_zero [0.015646s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_create_volume_without_passing_size [0.015834s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_delete_invalid_volume_id [0.028085s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_delete_volume_without_passing_volume_id [0.013720s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_detach_volumes_with_invalid_volume_id [0.026988s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_get_invalid_volume_id [0.031782s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_get_volume_without_passing_volume_id [0.013730s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_list_volumes_detail_with_invalid_status [0.043935s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_list_volumes_detail_with_nonexistent_name [0.039472s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_list_volumes_with_invalid_status [0.030010s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_list_volumes_with_nonexistent_name [0.034964s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_reserve_volume_with_negative_volume_status [0.136108s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_reserve_volume_with_nonexistent_volume_id [0.028122s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_unreserve_volume_with_nonexistent_volume_id [0.028183s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_update_volume_with_empty_volume_id [0.013411s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_update_volume_with_invalid_volume_id [0.025041s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_update_volume_with_nonexistent_volume_id [0.033207s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_delete_nonexistent_volume_id [0.027798s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_extend_with_None_size [0.015522s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_extend_with_non_number_size [0.015778s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_extend_with_nonexistent_volume_id [0.030636s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_extend_with_size_smaller_than_original_size [0.017357s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_extend_without_passing_volume_id [0.028117s] ... ok
{2} tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_volume_get_nonexistent_volume_id [0.027764s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_create_snapshot_with_nonexistent_volume_id [0.141328s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_force_detach_volume [10.278344s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_create_snapshot_without_passing_volume_id [0.078619s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_list_snapshot_invalid_param_limit [0.015994s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_list_snapshots_invalid_param_marker [0.024537s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_list_snapshots_invalid_param_sort [0.018863s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_volume_force_delete_when_volume_is_attaching [3.617453s] ... ok
{1} tempest.api.volume.test_volumes_snapshots_negative.VolumesSnapshotNegativeTestJSON.test_volume_from_snapshot_decreasing_size [4.705805s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_volume_force_delete_when_volume_is_creating [3.668389s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_volume_force_delete_when_volume_is_error [3.667900s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_volume_force_delete_when_volume_is_maintenance [2.803134s] ... ok
{0} tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_volume_reset_status [2.858211s] ... ok
{0} tempest.api.volume.admin.test_volumes_list.VolumesListAdminTestJSON.test_volume_list_param_tenant [2.639893s] ... ok
{2} tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_delete_with_volume_in_use [37.963148s] ... ok
{2} tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_get_list_update_delete [3.500272s] ... ok
{0} tempest.api.volume.test_image_metadata.VolumesImageMetadata.test_update_show_delete_image_metadata [0.237049s] ... ok
{0} tempest.api.volume.test_volume_metadata.VolumesMetadataTest.test_crud_volume_metadata [0.344806s] ... ok
{0} tempest.api.volume.test_volume_metadata.VolumesMetadataTest.test_update_show_volume_metadata_item [0.226694s] ... ok
{2} tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_offline_delete_online [21.349055s] ... ok
{2} tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_volume_from_snapshot [8.262602s] ... ok
{0} tempest.api.volume.test_volume_transfers.VolumesTransfersTest.test_create_get_list_accept_volume_transfer [4.665435s] ... ok
{0} tempest.api.volume.test_volume_transfers.VolumesTransfersTest.test_create_list_delete_volume_transfer [3.783655s] ... ok
{2} tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_volume_from_snapshot_no_size [8.471299s] ... ok
{0} tempest.api.volume.test_volumes_extend.VolumesExtendAttachedTest.test_extend_attached_volume [15.434527s] ... ok

==============================
Failed 3 tests - output below:
==============================

tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_attach_attached_volume_to_different_server[id-ee37a796-2afb-11e7-bc0f-fa163e65f5ce,negative]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:49,690 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:49,691 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:50,500 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.808s
2022-07-20 17:05:50,501 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-324477502"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:49 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2304', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-905c9fa7-d68a-4e39-b57b-a6caf374c2de', 'x-compute-request-id': 'req-905c9fa7-d68a-4e39-b57b-a6caf374c2de', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEpAIBAAKCAQEAxfYvGd4+NXBAbl/leXnsULxTeVp16t+3xZwb+idtZzyyNg9r\\n64X1o/oUJqgEXOk+An7APay1rVy6mpwNYv2mHzs88mfKEcuy9k8A2E+0Y/Hboaz2\\nadzxa7VqLFRXyCZbexaimcUCFUtMaKrNLYC8tiTYPJEM3sheHlqmyeh92cVagvVZ\\nj49MJ0yTh3r0KD6yLhrDF3EhLR6mnCbc7T1CQ9+hoxmbl8jfyU1V3EVv8Q19WKAq\\nAkAnYeRtpGgsnpoQ3QPvVw3FPaLDc/X/SRxvezPxVwfL+ISHxmOrdQ4U07FnZ9UP\\nhPR8XFfUgKAa2r1C5QaUgWsEb4jqyWtpBHc7fQIDAQABAoIBAQCJ5l2XQobJSQHJ\\nIYpEHdetwhLQBWEBFYj54i5nCxIeCV0HZaTC85VS/gENkJtBccUdjdgy3l3Mfz0K\\nOMzmeVVAik6BeiV8Ug6/n/cxuAwsVy2tKUSaKCwQ4NYuPS7NIVM2omTwgxlZZhO7\\nEchN+1D5/R6Yyl5RzvgpYvKu0gLhMGyM8r6Q19RC0YL2sLbovrrV53E0+2Rvla4E\\nz6ANcb+2/lr+oYlejZ8kYPnd+qlrJcRzrAFw8d+nhanseJWj4iysBiMd3Uit/isW\\nsi3b2gejEGgTQNvvXQBQtP6BQmtjO6Kh3ZdA4kQ1CguopMTO/TXyjO2BtAsYL/vW\\nm5RfsgnNAoGBAOZZTCpk1X007LA4RoK/K3GNE8Esf5PCHOW0/reA88oRq5tzJ0Xb\\n5ujbzQuqw+yihaZ09tEyZkEYK0OWmiJBSQb6kTVQw8iQ979t2qT3d47ucJFEYnQI\\nvvwnsvNncdnLH4HCk8hMH7HH8lWexHqYqj66RxCrZ16y5lEJAYyF03nnAoGBANwB\\nms8uAnVz6NSQ69ESdqjGHSrzgLzvrKljTExyAI3Xso7QhUB5rizcYAdEldfynHRz\\n1XXruuAbNQgmbiJt6nUJmdUrqS7K/R1rysUJEQsdseEJU5iXDMStkigj8giAHz8a\\n5NOPBX36sWgCzLf8IEGICRRmXZCpmlFx6VqbMNr7AoGBAMILZ4Yu+0lGVDz+qydp\\nM4eseH+6pJ4sX3uCRTEAiF4pFI8XKnZHEPYIc2rop7OoFT5sOZ9w/YLIgWmmbKF+\\nra4bVke7ibJjrNCuEgn2DdlyM5GsMePdmkWAi9dPxTDbU+dTqnqI5go1jYdi/9Dm\\n2kONWGBKhAHaYvrQw2VFNyjxAoGACttBamvYzzbzDFpCaMTCej2cftwZRDmHiaxO\\nvY76nAVC2G1Nxgq7H5eYXYNy6X8dXVnB9Nm3FQwCp+5NjQFjinb40l4fMSHvL558\\nGREDeEr01igBqgv6I1J1Xem4Ldc0s4Z+ODpciQTv8DQDKikU5mbyG8GZaGQWK2K1\\nozT5SjUCgYAiQcbtzPSjt74KAlpnmS4RW0+cbH54lfLRTBK7uwT+/kGyNwTzY1Ni\\ns9awRZJuF+3uoOlMb6OVtloz/d38vPvTF3UCvH1NsQVOSf4yQgtnKw3mgxB4QxIi\\nKAeLwvDWQyEVSJjSbDtO8bagvkQWqH5t3wt0/PePQ6Ji3LpRVbXfHw==\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-324477502", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF9i8Z3j41cEBuX+V5eexQvFN5WnXq37fFnBv6J21nPLI2D2vrhfWj+hQmqARc6T4CfsA9rLWtXLqanA1i/aYfOzzyZ8oRy7L2TwDYT7Rj8duhrPZp3PFrtWosVFfIJlt7FqKZxQIVS0xoqs0tgLy2JNg8kQzeyF4eWqbJ6H3ZxVqC9VmPj0wnTJOHevQoPrIuGsMXcSEtHqacJtztPUJD36GjGZuXyN/JTVXcRW/xDX1YoCoCQCdh5G2kaCyemhDdA+9XDcU9osNz9f9JHG97M/FXB8v4hIfGY6t1DhTTsWdn1Q+E9HxcV9SAoBravULlBpSBawRviOrJa2kEdzt9 Generated-by-Nova", "fingerprint": "42:d2:f7:96:5b:ec:6d:24:c4:14:05:7b:16:9a:55:c0", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:50,506 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-324477502 created
2022-07-20 17:05:51,714 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 1.206s
2022-07-20 17:05:51,715 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'app
    lication/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:50 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-f1a5015e-c5ce-4772-886f-7706c21fb2fe', 'x-compute-request-id': 'req-f1a5015e-c5ce-4772-886f-7706c21fb2fe', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:51,715 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAxfYvGd4+NXBAbl/leXnsULxTeVp16t+3xZwb+idtZzyyNg9r\n64X1o/oUJqgEXOk+An7APay1rVy6mpwNYv2mHzs88mfKEcuy9k8A2E+0Y/Hboaz2\nadzxa7VqLFRXyCZbexaimcUCFUtMaKrNLYC8tiTYPJEM3sheHlqmyeh92cVagvVZ\nj49MJ0yTh3r0KD6yLhrDF3EhLR6mnCbc7T1CQ9+hoxmbl8jfyU1V3EVv8Q19WKAq\nAkAnYeRtpGgsnpoQ3QPvVw3FPaLDc/X/SRxvezPxVwfL+ISHxmOrdQ4U07FnZ9UP\nhPR8XFfUgKAa2r1C5QaUgWsEb4jqyWtpBHc7fQIDAQABAoIBAQCJ5l2XQobJSQHJ\nIYpEHdetwhLQBWEBFYj54i5nCxIeCV0HZaTC85VS/gENkJtBccUdjdgy3l3Mfz0K\nOMzmeVVAik6BeiV8Ug6/n/cxuAwsVy2tKUSaKCwQ4NYuPS7NIVM2omTwgxlZZhO7\nEchN+1D5/R6Yyl5RzvgpYvKu0gLhMGyM8r6Q19RC0YL2sLbovrrV53E0+2Rvla4E\nz6ANcb+2/lr+oYlejZ8kYPnd+qlrJcRzrAFw8d+nhanseJWj4iysBiMd3Uit/isW\nsi3b2gejEGgTQNvvXQBQtP6BQmtjO6Kh3ZdA4kQ1CguopMTO/TXyjO2BtAsYL/vW\nm5RfsgnNAoGBAOZZTCpk1X007LA4RoK/K3GNE8Esf5PCHOW0/reA88oRq5tzJ0Xb\n5ujbzQuqw+yihaZ09tEyZkEYK0OWmiJBSQb6kTVQw8iQ979t2qT3d47ucJFEYnQI\nvvwnsvNncdnLH4HCk8hMH7HH8lWexHqYqj66RxCrZ16y5lEJAYyF03nnAoGBANwB\nms8uAnVz6NSQ69ESdqjGHSrzgLzvrKljTExyAI3Xso7QhUB5rizcYAdEldfynHRz\n1XXruuAbNQgmbiJt6nUJmdUrqS7K/R1rysUJEQsdseEJU5iXDMStkigj8giAHz8a\n5NOPBX36sWgCzLf8IEGICRRmXZCpmlFx6VqbMNr7AoGBAMILZ4Yu+0lGVDz+qydp\nM4eseH+6pJ4sX3uCRTEAiF4pFI8XKnZHEPYIc2rop7OoFT5sOZ9w/YLIgWmmbKF+\nra4bVke7ibJjrNCuEgn2DdlyM5GsMePdmkWAi9dPxTDbU+dTqnqI5go1jYdi/9Dm\n2kONWGBKhAHaYvrQw2VFNyjxAoGACttBamvYzzbzDFpCaMTCej2cftwZRDmHiaxO\nvY76nAVC2G1Nxgq7H5eYXYNy6X8dXVnB9Nm3FQwCp+5NjQFjinb40l4fMSHvL558\nGREDeEr01igBqgv6I1J1Xem4Ldc0s4Z+ODpciQTv8DQDKikU5mbyG8GZaGQWK2K1\nozT5SjUCgYAiQcbtzPSjt74KAlpnmS4RW0+cbH54lfLRTBK7uwT+/kGyNwTzY1Ni\ns9awRZJuF+3uoOlMb6OVtloz/d38vPvTF3UCvH1NsQVOSf4yQgtnKw3mgxB4QxIi\nKAeLwvDWQyEVSJjSbDtO8bagvkQWqH5t3wt0/PePQ6Ji3LpRVbXfHw==\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-324477502', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF9i8Z3j41cEBuX+V5eexQvFN5WnXq37fFnBv6J21nPLI2D2vrhfWj+hQmqARc6T4CfsA9rLWtXLqanA1i/aYfOzzyZ8oRy7L2TwDYT7Rj8duhrPZp3PFrtWosVFfIJlt7FqKZxQIVS0xoqs0tgLy2JNg8kQzeyF4eWqbJ6H3ZxVqC9VmPj0wnTJOHevQoPrIuGsMXcSEtHqacJtztPUJD36GjGZuXyN/JTVXcRW/xDX1YoCoCQCdh5G2kaCyemhDdA+9XDcU9osNz9f9JHG97M/FXB8v4hIfGY6t1DhTTsWdn1Q+E9HxcV9SAoBravULlBpSBawRviOrJa2kEdzt9 Generated-by-Nova', 'fingerprint': '42:d2:f7:96:5b:ec:6d:24:c4:14:05:7b:16:9a:55:c0', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:51,763 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-324477502 0.046s
2022-07-20 17:05:51,763 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:51 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-87d1417d-bde1-4e12-a9d8-8c84768190fa', 'x-compute-request-id': 're
    q-87d1417d-bde1-4e12-a9d8-8c84768190fa', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-324477502'}
        Body: b''


tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_attach_attached_volume_to_same_server[id-aab919e2-d992-4cbb-a4ed-745c2475398c,negative]
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:51,772 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:51,773 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:52,185 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.412s
2022-07-20 17:05:52,186 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-1017563030"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:51 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2301', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-06fd85b0-7687-4123-bf0e-d0e37ad0c54b', 'x-compute-request-id': 'req-06fd85b0-7687-4123-bf0e-d0e37ad0c54b', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEowIBAAKCAQEA2QoR/6xRmpZ0TO1W7R9qurwhcEunnRoReetC/AGMCOYxHqe9\\nUAS9iw+wlXPZszLNtJhFnk+yUVxb/TIB0iYBmZ6wh9EDNjwlQQLgcQgLiXeKQsIa\\npCJOmd/0Dw2BpKWhXLsITxdwKwZcHzP3vk51ozZ2J7pz7nLOsrCVFXdZZoAJVwdR\\nz5xszoVKLFuZ1fMl4MyB40q/jPD6utWDx5uugk4ZMTi7C4BkAwIRywBje1hxCleJ\\nZy6wLGX5WyCqcqjpHP4MaqMvgT8fcrplz2YAuJPyH1Faco/1SQQFMp0Tv1UaSi5A\\nmAGPrndhInRh3lhWXi1JGmZtJ8wd08/D+2ra5wIDAQABAoIBAB5iiYiIwFfrDlci\\ntxO1XUTNR8Un4kxdNOsjo5oSQV+RknjfNOK59ys7xBX4RRcQWroYw05Zi/ZV/s7g\\nrF6WUY0HKWGqQk/adcC3PWK1pJ/XK3UTJZWq8+QY9VsSIf9B7OhFivE/r8VmO4lm\\nxh1PcKqr2jjPoqFUU1my3PxHXC28JwZUDhyecv0WIt2udzKIsdpv6hYqD6FxJV+F\\ngyRK++/JhiaQZCas8OtDA0hqtaxKTcdE3OAuGvIp/EQ358nkw3LIQkqqHzB6y0mC\\noSF6iVU1acR2nBnO9SfG7l9j//Hjm77HFo+/j98sRJafimC5B25J3U54dEWOJrqG\\nGdRv6ekCgYEA9NkcrfJhoRrzy9sqDRNaYSObC34cXxTCDbVOyyG/IITbyavv44Ef\\nobyeDIcdLUV85D5QJr4PjkqkrxyfjQKl/W53tPLiJQ5zaFDtxOhrp9g3N0FPTVML\\nROhZ9ZemyIY1D4X/N/2zDbFJfdmRAfV1Nrm/zvStpGIi3332Cg2f3yMCgYEA4uy2\\neqmDBEypoUFkTon1ecpz/nFXnx+EbCbmbyjiqKSJxyI3t9eUePFuaawSz1YHdzZ8\\nES+U2NPADOHWWuk605ZQZ7yavE5pgdS1bJVKWOIu1PyiP47fieFflirQXaQ5o2gq\\n+nYH3ujkAp8hHx04RqPqy8BG86ER5UgSW3dF020CgYAVA+GDSI96nW6Za6kzUBrs\\nxXqURPG4c3aoaIxnwPC/oMegiqJfW4DUh/TkzGADt7gdev+0I5IAO4XhBcrn9nc6\\nxlV98W7ZkWD0biXKRcyfrl4m3vMoht0rv+mgu7Bz+5joSS77pknM/g95vsfEbEXw\\nOYcuAzA4MLgfiJcqi7rSEwKBgQDAoNAGL/7Xl3wnNqs/QDzwtbrhMrV+jfKLHDpg\\nAgTlw0Zxk8pYdNfEEq33ZepRtmV//PA0Zn+jz5wnU03yvikBk4eNh7ySPL2zSCz5\\nj4EdEmNOyWWxLkbzdCz//DgERXPoEnTpR2hHAMsMrqgfEV7EGEEn1IBmL0RRrWxn\\n2EedwQKBgBpvqOXljiZYhdGJUXReOdnGi2V1rBaDR8m+xEkmTJlECuguU4UCk/t4\\n2zqiTtCMUXurcYz+NdLcwaj4uTFjUfJqhNhvo7bJPVjlGeY1I/HWyU9EQSFcosWU\\nd9oC0D9VMEz+x/GIPdVkxuwSNZEfWf8fggryjnwNinGAuctLb8T8\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-1017563030", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZChH/rFGalnRM7VbtH2q6vCFwS6edGhF560L8AYwI5jEep71QBL2LD7CVc9mzMs20mEWeT7JRXFv9MgHSJgGZnrCH0QM2PCVBAuBxCAuJd4pCwhqkIk6Z3/QPDYGkpaFcuwhPF3ArBlwfM/e+TnWjNnYnunPucs6ysJUVd1lmgAlXB1HPnGzOhUosW5nV8yXgzIHjSr+M8Pq61YPHm66CThkxOLsLgGQDAhHLAGN7WHEKV4lnLrAsZflbIKpyqOkc/gxqoy+BPx9yumXPZgC4k/IfUVpyj/VJBAUynRO/VRpKLkCYAY+ud2EidGHeWFZeLUkaZm0nzB3Tz8P7atrn Generated-by-Nova", "fingerprint": "1d:46:7b:3a:a6:1d:e0:8f:cd:0e:94:ad:40:52:cf:b4", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:52,189 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-1017563030 created
2022-07-20 17:05:52,259 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 0.068s
2022-07-20 17:05:52,259 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'appl
    ication/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-1901deee-3f38-497d-8ca7-c9497a767f05', 'x-compute-request-id': 'req-1901deee-3f38-497d-8ca7-c9497a767f05', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:52,260 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA2QoR/6xRmpZ0TO1W7R9qurwhcEunnRoReetC/AGMCOYxHqe9\nUAS9iw+wlXPZszLNtJhFnk+yUVxb/TIB0iYBmZ6wh9EDNjwlQQLgcQgLiXeKQsIa\npCJOmd/0Dw2BpKWhXLsITxdwKwZcHzP3vk51ozZ2J7pz7nLOsrCVFXdZZoAJVwdR\nz5xszoVKLFuZ1fMl4MyB40q/jPD6utWDx5uugk4ZMTi7C4BkAwIRywBje1hxCleJ\nZy6wLGX5WyCqcqjpHP4MaqMvgT8fcrplz2YAuJPyH1Faco/1SQQFMp0Tv1UaSi5A\nmAGPrndhInRh3lhWXi1JGmZtJ8wd08/D+2ra5wIDAQABAoIBAB5iiYiIwFfrDlci\ntxO1XUTNR8Un4kxdNOsjo5oSQV+RknjfNOK59ys7xBX4RRcQWroYw05Zi/ZV/s7g\nrF6WUY0HKWGqQk/adcC3PWK1pJ/XK3UTJZWq8+QY9VsSIf9B7OhFivE/r8VmO4lm\nxh1PcKqr2jjPoqFUU1my3PxHXC28JwZUDhyecv0WIt2udzKIsdpv6hYqD6FxJV+F\ngyRK++/JhiaQZCas8OtDA0hqtaxKTcdE3OAuGvIp/EQ358nkw3LIQkqqHzB6y0mC\noSF6iVU1acR2nBnO9SfG7l9j//Hjm77HFo+/j98sRJafimC5B25J3U54dEWOJrqG\nGdRv6ekCgYEA9NkcrfJhoRrzy9sqDRNaYSObC34cXxTCDbVOyyG/IITbyavv44Ef\nobyeDIcdLUV85D5QJr4PjkqkrxyfjQKl/W53tPLiJQ5zaFDtxOhrp9g3N0FPTVML\nROhZ9ZemyIY1D4X/N/2zDbFJfdmRAfV1Nrm/zvStpGIi3332Cg2f3yMCgYEA4uy2\neqmDBEypoUFkTon1ecpz/nFXnx+EbCbmbyjiqKSJxyI3t9eUePFuaawSz1YHdzZ8\nES+U2NPADOHWWuk605ZQZ7yavE5pgdS1bJVKWOIu1PyiP47fieFflirQXaQ5o2gq\n+nYH3ujkAp8hHx04RqPqy8BG86ER5UgSW3dF020CgYAVA+GDSI96nW6Za6kzUBrs\nxXqURPG4c3aoaIxnwPC/oMegiqJfW4DUh/TkzGADt7gdev+0I5IAO4XhBcrn9nc6\nxlV98W7ZkWD0biXKRcyfrl4m3vMoht0rv+mgu7Bz+5joSS77pknM/g95vsfEbEXw\nOYcuAzA4MLgfiJcqi7rSEwKBgQDAoNAGL/7Xl3wnNqs/QDzwtbrhMrV+jfKLHDpg\nAgTlw0Zxk8pYdNfEEq33ZepRtmV//PA0Zn+jz5wnU03yvikBk4eNh7ySPL2zSCz5\nj4EdEmNOyWWxLkbzdCz//DgERXPoEnTpR2hHAMsMrqgfEV7EGEEn1IBmL0RRrWxn\n2EedwQKBgBpvqOXljiZYhdGJUXReOdnGi2V1rBaDR8m+xEkmTJlECuguU4UCk/t4\n2zqiTtCMUXurcYz+NdLcwaj4uTFjUfJqhNhvo7bJPVjlGeY1I/HWyU9EQSFcosWU\nd9oC0D9VMEz+x/GIPdVkxuwSNZEfWf8fggryjnwNinGAuctLb8T8\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-1017563030', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZChH/rFGalnRM7VbtH2q6vCFwS6edGhF560L8AYwI5jEep71QBL2LD7CVc9mzMs20mEWeT7JRXFv9MgHSJgGZnrCH0QM2PCVBAuBxCAuJd4pCwhqkIk6Z3/QPDYGkpaFcuwhPF3ArBlwfM/e+TnWjNnYnunPucs6ysJUVd1lmgAlXB1HPnGzOhUosW5nV8yXgzIHjSr+M8Pq61YPHm66CThkxOLsLgGQDAhHLAGN7WHEKV4lnLrAsZflbIKpyqOkc/gxqoy+BPx9yumXPZgC4k/IfUVpyj/VJBAUynRO/VRpKLkCYAY+ud2EidGHeWFZeLUkaZm0nzB3Tz8P7atrn Generated-by-Nova', 'fingerprint': '1d:46:7b:3a:a6:1d:e0:8f:cd:0e:94:ad:40:52:cf:b4', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:52,297 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-1017563030 0.036s
2022-07-20 17:05:52,298 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-b457e327-bb0d-4ecc-9ec0-86da7e0c918d', 'x-compute-request-id': 'req-b
    457e327-bb0d-4ecc-9ec0-86da7e0c918d', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-1017563030'}
        Body: b''


tempest.api.compute.volumes.test_attach_volume_negative.AttachVolumeNegativeTest.test_delete_attached_volume[id-a313b5cd-fbd0-49cc-94de-870e99f763c7,negative]
--------------------------------------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}


Captured traceback-1:
~~~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 445, in _setUp
    floating_network_name=self._floating_network_name)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 245, in create_validation_resources
    LOG.exception(msg, prov_exc, cleanup_exc)

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

      File "/usr/local/lib/python3.6/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/validation_resources.py", line 217, in create_validation_resources
    pool=floating_network_name))

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/floating_ips_client.py", line 66, in create_floating_ip
    resp, body = self.post(url, post_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 299, in post
    return self.request('POST', url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 703, in request
    self._error_checker(resp, resp_body)

      File "/usr/local/lib/python3.6/site-packages/tempest/lib/common/rest_client.py", line 809, in _error_checker
    raise exceptions.NotFound(resp_body, resp=resp)

    tempest.lib.exceptions.NotFound: Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}

    
During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/usr/local/lib/python3.6/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)

    fixtures.fixture.SetupError: {}


Captured pythonlogging:
~~~~~~~~~~~~~~~~~~~~~~~
    2022-07-20 17:05:52,304 11199 DEBUG    [tempest.lib.common.validation_resources] Requested setup of ValidationResources keypair True, floating IP True, security group False
2022-07-20 17:05:52,305 11199 DEBUG    [tempest.lib.common.validation_resources] Requested validation resources keypair True, floating IP True, security group False
2022-07-20 17:05:52,450 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 200 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs 0.145s
2022-07-20 17:05:52,451 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"keypair": {"name": "tempest-keypair-568944202"}}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '2300', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-76f5124f-d800-4f11-b141-c9ea4da40397', 'x-compute-request-id': 'req-76f5124f-d800-4f11-b141-c9ea4da40397', 'connection': 'close', 'content-type': 'application/json', 'status': '200', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs'}
        Body: b'{"keypair": {"private_key": "-----BEGIN RSA PRIVATE KEY-----\\nMIIEogIBAAKCAQEAwmdheM+MLKcROecta5ZWt1HvUpehE7AfqdNIOWqWZlOvcQZK\\nOlvfFiZFlS3wWsYXD9OJjr0AiQLdejbc8hG5DHpBML59kDJLDjGhez5+7a8ujiA3\\nwMg9ohN3QjA5v0OfCHNH3jhrM1Jl7JLQ21deQXgfAqky4as/prr8w/wiIb63C9a2\\n5YvgQs7ftL4FaZhDEr39QC6Bwcj0nLrhSxhGe1XXy5isWyZes5ql7Cr2BLEQOLI8\\n7B7UsrqcZyA2Pbi7hTHaNmWDaP8jBUGbefxbqoeV7rxGt1NLK+wysP3Eo41sYSYD\\nlMGOgB6qR5360FokfhndGp7JkJ4BPDnJWGiMLwIDAQABAoIBABG9FSvM5GF+rRe3\\nfHGAulDn7QqAQ3Zkb78zRDfY/fhAUpXhmQxSLbz7qQW/t1rREHGlP7wCivX1iPgJ\\n4YdFDrmQvjoQZ6ysqiSVasKwJSzS+1CEqBGzM8yCMjOb6ukE5pIC0t/4DfAU6K/5\\nhY0+H5+hslKv1bC5y4kPLtlDPGoPsCzVa9TRmPSH6lAk6aeG2Wj//KJ6fGccJ7SM\\nw4bkBfsgFtVPeDmfel+RVcmZ9mIN0tD/18RkH2uGU078ztE1pv8sohbI3hN7l/aU\\nvpQS5mHJybt6oNEb8qxYRsJhSSWzDE5CSyUEzHCHcgDEswtY1o0X9a6V6fC/msek\\nxQ79feECgYEA6JBo89Y3fhiPelh3iq8OWUyLE3Uc4C7wLWnaXtk+1kw0ptRQhkpv\\nxLtVYIdoW+ui0ne4apW035u/w68DgDlSQe/7m4I/2mNIT8Lxm27IkS0VeIszelEY\\n2SriRnTVmB0hNzmTs6VL0LCfx/Wpq7RiGZrNztazgGerf1I67bLhuyUCgYEA1f6H\\nP3QgmAOCveM+WrA+L6VC8ImFxy1zSPdwANUvtF+AUMGV/vnzj+hbpSkuI8WndiQu\\nBChbEVvp8ank+0gwspHNkJSDSlAhh6Z0xD8x+TVY9qKIySg1JXLJD+jvADfQ+wyT\\nc2k2UjdxE6CbnbSL6RJHp+12IwgA6V+nqwaCU8MCgYAEV+4d37pZmIvVdSGGbY6P\\nDGbsjhtj9Hx33Ko/az9JMVMqany2hV1hBz6o9t50GQqJc8L1+qXOJ1KFjRc7pdZr\\ndNf2J5CZu5D2LGXmyULlsznbbn4forQcGjjvp+71UFX2ehTQHh40X5gcW/I3Sr8q\\nS0HcwxXHKCiD0D1ZgyXEIQKBgHCTZzk1cVQnPKeCnbH916kfCpkZ79u5iFWRfkWh\\n4WfFee6B+NPbUIubVGMNx+0ftRpMrDyZslbugKMWmpSrBJtcYsU1q9/zScBgDDuV\\nd0fADd4p4UXZtiPOQAHzq4/0zSbVFdj4N5CHBCCsNFGBwrzJVhL8tFJ3ims7XCx3\\nzyYbAoGAFj+ruYL6UFQtfa+VowUb0JKJnHe2fe2kxMxYmRASIK73Zu1Yq6iO6jvO\\nLhuZB+FcdmOjBM5GKvFnH8X4JTKGd8qCdddBcKn19MBa5Fd8X1X9ncoYNIN9WDiL\\nEgYVNgeU4SNsukSLn8RcGZwCsfv5OoTT1LPaXAOgs1H8n8lfSJ8=\\n-----END RSA PRIVATE KEY-----\\n", "name": "tempest-keypair-568944202", "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZ2F4z4wspxE55y1rlla3Ue9Sl6ETsB+p00g5apZmU69xBko6W98WJkWVLfBaxhcP04mOvQCJAt16NtzyEbkMekEwvn2QMksOMaF7Pn7try6OIDfAyD2iE3dCMDm/Q58Ic0feOGszUmXsktDbV15BeB8CqTLhqz+muvzD/CIhvrcL1rbli+BCzt+0vgVpmEMSvf1ALoHByPScuuFLGEZ7VdfLmKxbJl6zmqXsKvYEsRA4sjzsHtSyupxnIDY9uLuFMdo2ZYNo/yMFQZt5/Fuqh5XuvEa3U0sr7DKw/cSjjWxhJgOUwY6AHqpHnfrQWiR+Gd0ansmQngE8OclYaIwv Generated-by-Nova", "fingerprint": "70:c8:f3:29:c7:e0:b8:29:e7:5a:92:cd:33:65:57:78", "user_id": "608a04c2abc641c6bd8a22d619bad944"}}'
2022-07-20 17:05:52,454 11199 DEBUG    [tempest.lib.common.validation_resources] Validation resource key tempest-keypair-568944202 created
2022-07-20 17:05:52,561 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 404 POST http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips 0.106s
2022-07-20 17:05:52,562 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'applica
    tion/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"pool": null}
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '73', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-076629df-42e8-4d01-8453-5406b16870bc', 'x-compute-request-id': 'req-076629df-42e8-4d01-8453-5406b16870bc', 'connection': 'close', 'content-type': 'application/json; charset=UTF-8', 'status': '404', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-floating-ips'}
        Body: b'{"itemNotFound": {"code": 404, "message": "Floating IP pool not found."}}'
2022-07-20 17:05:52,562 11199 DEBUG    [tempest.lib.common.validation_resources] Error while provisioning validation resources Object not found
Details: {'code': 404, 'message': 'Floating IP pool not found.'}. Trying to cleanup what we provisioned so far: {'keypair': {'private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAwmdheM+MLKcROecta5ZWt1HvUpehE7AfqdNIOWqWZlOvcQZK\nOlvfFiZFlS3wWsYXD9OJjr0AiQLdejbc8hG5DHpBML59kDJLDjGhez5+7a8ujiA3\nwMg9ohN3QjA5v0OfCHNH3jhrM1Jl7JLQ21deQXgfAqky4as/prr8w/wiIb63C9a2\n5YvgQs7ftL4FaZhDEr39QC6Bwcj0nLrhSxhGe1XXy5isWyZes5ql7Cr2BLEQOLI8\n7B7UsrqcZyA2Pbi7hTHaNmWDaP8jBUGbefxbqoeV7rxGt1NLK+wysP3Eo41sYSYD\nlMGOgB6qR5360FokfhndGp7JkJ4BPDnJWGiMLwIDAQABAoIBABG9FSvM5GF+rRe3\nfHGAulDn7QqAQ3Zkb78zRDfY/fhAUpXhmQxSLbz7qQW/t1rREHGlP7wCivX1iPgJ\n4YdFDrmQvjoQZ6ysqiSVasKwJSzS+1CEqBGzM8yCMjOb6ukE5pIC0t/4DfAU6K/5\nhY0+H5+hslKv1bC5y4kPLtlDPGoPsCzVa9TRmPSH6lAk6aeG2Wj//KJ6fGccJ7SM\nw4bkBfsgFtVPeDmfel+RVcmZ9mIN0tD/18RkH2uGU078ztE1pv8sohbI3hN7l/aU\nvpQS5mHJybt6oNEb8qxYRsJhSSWzDE5CSyUEzHCHcgDEswtY1o0X9a6V6fC/msek\nxQ79feECgYEA6JBo89Y3fhiPelh3iq8OWUyLE3Uc4C7wLWnaXtk+1kw0ptRQhkpv\nxLtVYIdoW+ui0ne4apW035u/w68DgDlSQe/7m4I/2mNIT8Lxm27IkS0VeIszelEY\n2SriRnTVmB0hNzmTs6VL0LCfx/Wpq7RiGZrNztazgGerf1I67bLhuyUCgYEA1f6H\nP3QgmAOCveM+WrA+L6VC8ImFxy1zSPdwANUvtF+AUMGV/vnzj+hbpSkuI8WndiQu\nBChbEVvp8ank+0gwspHNkJSDSlAhh6Z0xD8x+TVY9qKIySg1JXLJD+jvADfQ+wyT\nc2k2UjdxE6CbnbSL6RJHp+12IwgA6V+nqwaCU8MCgYAEV+4d37pZmIvVdSGGbY6P\nDGbsjhtj9Hx33Ko/az9JMVMqany2hV1hBz6o9t50GQqJc8L1+qXOJ1KFjRc7pdZr\ndNf2J5CZu5D2LGXmyULlsznbbn4forQcGjjvp+71UFX2ehTQHh40X5gcW/I3Sr8q\nS0HcwxXHKCiD0D1ZgyXEIQKBgHCTZzk1cVQnPKeCnbH916kfCpkZ79u5iFWRfkWh\n4WfFee6B+NPbUIubVGMNx+0ftRpMrDyZslbugKMWmpSrBJtcYsU1q9/zScBgDDuV\nd0fADd4p4UXZtiPOQAHzq4/0zSbVFdj4N5CHBCCsNFGBwrzJVhL8tFJ3ims7XCx3\nzyYbAoGAFj+ruYL6UFQtfa+VowUb0JKJnHe2fe2kxMxYmRASIK73Zu1Yq6iO6jvO\nLhuZB+FcdmOjBM5GKvFnH8X4JTKGd8qCdddBcKn19MBa5Fd8X1X9ncoYNIN9WDiL\nEgYVNgeU4SNsukSLn8RcGZwCsfv5OoTT1LPaXAOgs1H8n8lfSJ8=\n-----END RSA PRIVATE KEY-----\n', 'name': 'tempest-keypair-568944202', 'public_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCZ2F4z4wspxE55y1rlla3Ue9Sl6ETsB+p00g5apZmU69xBko6W98WJkWVLfBaxhcP04mOvQCJAt16NtzyEbkMekEwvn2QMksOMaF7Pn7try6OIDfAyD2iE3dCMDm/Q58Ic0feOGszUmXsktDbV15BeB8CqTLhqz+muvzD/CIhvrcL1rbli+BCzt+0vgVpmEMSvf1ALoHByPScuuFLGEZ7VdfLmKxbJl6zmqXsKvYEsRA4sjzsHtSyupxnIDY9uLuFMdo2ZYNo/yMFQZt5/Fuqh5XuvEa3U0sr7DKw/cSjjWxhJgOUwY6AHqpHnfrQWiR+Gd0ansmQngE8OclYaIwv Generated-by-Nova', 'fingerprint': '70:c8:f3:29:c7:e0:b8:29:e7:5a:92:cd:33:65:57:78', 'user_id': '608a04c2abc641c6bd8a22d619bad944'}}
2022-07-20 17:05:52,595 11199 INFO     [tempest.lib.common.rest_client] Request (ValidationResourcesFixture:setUp): 202 DELETE http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-568944202 0.031s
2022-07-20 17:05:52,595 11199 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Wed, 20 Jul 2022 14:05:52 GMT', 'server': 'Apache/2.4.41 (Ubuntu)', 'content-length': '0', 'openstack-api-version': 'compute 2.1', 'x-openstack-nova-api-version': '2.1', 'vary': 'OpenStack-API-Version,X-OpenStack-Nova-API-Version', 'x-openstack-request-id': 'req-ec95a74a-ff11-445c-b40d-34a7ef8c6146', 'x-compute-request-id': 'req-ec95a7
    4a-ff11-445c-b40d-34a7ef8c6146', 'connection': 'close', 'content-type': 'application/json', 'status': '202', 'content-location': 'http://[LB_IP_ADDRESS]:8774/v2.1/os-keypairs/tempest-keypair-568944202'}
        Body: b''



======
Totals
======
Ran: 222 tests in 343.5177 sec.
 - Passed: 213
 - Skipped: 6
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 3
Sum of execute time for each test: 557.2081 sec.

==============
Worker Balance
==============
 - Worker 0 (54 tests) => 0:05:43.517710
 - Worker 1 (75 tests) => 0:04:09.134049
 - Worker 2 (93 tests) => 0:05:24.696967
